// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpofhrddfdxvtshouezj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwb2ZocmRkZmR4dnRzaG91ZXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDQ3NTIsImV4cCI6MjA2Mzk4MDc1Mn0.iavCAsdLaHpJil7Ry0II_oNCjEsfIDCcPCpuE9CSCEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);